services:
  api:
    build:
      context: ../
      dockerfile: docker/dockerfile
    image: translation/api:latest
    container_name: TranslationAPI
    ports:
      - 14000:8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./llm_secrets.yaml:/app/docker/llm_secrets.yaml:ro
    command: ["python", "server.py", "-c", "docker/llm_config.yaml"]
    restart: unless-stopped
