services:
  api:
    build:
      context: ../
      dockerfile: docker/dockerfile
    image: translation/api:latest
    container_name: TranslationAPI
    ports:
      - 14000:8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
