FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

COPY ./docker/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

ARG model=facebook/nllb-200-3.3B

RUN pip install --no-cache-dir huggingface_hub[cli] && \
    huggingface-cli download ${model}

CMD ["python", "server.py", "-m", "${model}"]
